Flask_app/app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

user_post = db.Table('user_post',
                     db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id'))
)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    team = db.relationship('Post', secondary=user_post, backref='user', lazy="dynamic")
    


    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)

    def save(self):
        db.session.add(self)
        db.session.commit()

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    base_experience = db.Column(db.String, nullable=False)
    base_hp = db.Column(db.String, nullable=False)
    base_attack = db.Column(db.String, nullable=False)
    base_defense = db.Column(db.String, nullable=False)
    ability = db.Column(db.String, nullable=False)
    sprite_url = db.Column(db.String, nullable=False)
    

    def __init__(self, name, ability, base_experience, base_hp, base_attack, base_defense, sprite_url):
        self.name = name 
        self.ability = ability
        self.base_experience = base_experience
        self.base_hp = base_hp
        self.base_attack = base_attack
        self.base_defense = base_defense
        self.sprite_url = sprite_url
        

    def save(self):
        db.session.add(self)
        db.session.commit()

Flask_app/app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired 

class PokeForm(FlaskForm):
    poke_search = StringField('Name or ID of pokemon', validators=[DataRequired()])
    submit_btn = SubmitField('Find My Pokemon')

Flask_app/app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from app.models import db, User
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object(Config)

login_manager = LoginManager()

login_manager.init_app(app)
db.init_app(app)
migrate = Migrate(app, db)

# login manager meaasges and config
login_manager.login_view ='auth.login'
login_manager.login_message = 'You must login to gain access!'
login_manager.login_message_category = 'danger'


# import my blueprint onto app
from app.blueprints.auth import auth
from app.blueprints.main import main
from app.blueprints.post import post
from app.blueprints.api.routes import api

# register blueprint onto app
app.register_blueprint(auth)
app.register_blueprint(main)
app.register_blueprint(post)
app.register_blueprint(api)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

Flask_app/app/blueprints/api/routes.py
# from . import api
from flask import request, jsonify, Blueprint
from app.models import Post


api = Blueprint('api',__name__, url_prefix='/api')




@api.post('create_post')
def create_post_api():
    data = request.get_json


    new_post = Post(img_url= data['img_url'], caption= data['caption'])

Flask_app/app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

Flask_app/app/blueprints/main/routes.py
from . import main 
from flask import render_template, request
import requests
from . import main 
from .forms import PokeForm



@main.route('/')
def home():
    return render_template('home.html')

# @main.route('/user/<name>')
# def user(name):
#     return f'Hello {name}'

def poke_dic(pokemons):
    pokemon_dictionary = []
    for pokemon in pokemons:
        pokemon_dict = getPokenInfo(pokemon)
        pokemon_dictionary.append(pokemon_dict)
    return pokemon_dictionary

def getPokenInfo(pokemon):
    url = f'https://pokeapi.co/api/v2/pokemon/{pokemon}'
    response = requests.get(url)
    if response.ok:
        data = response.json()
        return {
            "name": data['name'],
            "ability": data['abilities'][0]['ability']['name'],
            "base_exp": data['base_experience'],
            "sprite_url": data['sprites']['back_default']
        }
    
@main.route('/pokemon', methods=['GET', 'POST'])
def pokemon():
    form = PokeForm()
    if request.method == 'POST':
        pokemon = request.form.get('pokemon')
        pokemon_go = getPokenInfo(pokemon)
        return render_template('pokemon.html', pokemon=pokemon_go)
    else:
        return render_template('pokemon.html', form=form)
    

Flask_app/app/blueprints/post/__init__.py
from flask import Blueprint

post = Blueprint('post', __name__, template_folder='post_templates')

from . import routes

Flask_app/app/blueprints/post/routes.py
from . import post 
from flask import render_template, request, redirect, url_for, flash
import requests
from app.blueprints.main.forms import PokeForm
from flask_login import login_required, current_user
from app.models import Post, db, User


# select_pokemon_route
def poke_dic(pokemons):
    pokemon_dictionary = []
    for pokemon in pokemons:
        pokemon_dict = getPokenInfo(pokemon)
        pokemon_dictionary.append(pokemon_dict)
    return pokemon_dictionary

def getPokenInfo(pokemon):
    url = f'https://pokeapi.co/api/v2/pokemon/{pokemon.lower()}'
    response = requests.get(url)
    if response.ok:
        data = response.json()
        return {
            "name": data['name'].lower(),
            "ability": data['abilities'][0]['ability']['name'],
            "base_exp": data['base_experience'],
            "sprite_url": data['sprites']['front_shiny'],
            "base_hp": data['stats'][0]['base_stat'],
            "base_attack": data['stats'][1]['base_stat'],
            "base_defense": data['stats'][2]['base_stat']

        }
    
@post.route('/select_pokemon', methods=['GET', 'POST'])
@login_required
def pokemon():
    form = PokeForm()
    if request.method == 'POST' and form.validate_on_submit:
        pokemon = request.form.get('pokemon').lower()
        query_poke = Post.query.filter_by(name = pokemon).first()
        if not query_poke: 
        # select_pokemon = form.select_pokemon.data
        # save pokemon here
            pokemon_go = getPokenInfo(pokemon)
            saved_pokemon = Post(name = pokemon_go['name'], base_experience = pokemon_go['base_exp'], base_hp = pokemon_go['base_hp'], ability = pokemon_go['ability'], base_attack = pokemon_go['base_attack'], base_defense = pokemon_go['base_defense'], sprite_url = pokemon_go['sprite_url'])
            saved_pokemon.save()
            flash('Pokemon Successfully Saved!')
            return render_template('select_pokemon.html', pokemon=pokemon_go)
        return render_template('select_pokemon.html', pokemon=query_poke)
    else:
        return render_template('select_pokemon.html', form=form)
    


@post.route("/catch_pokemon/<name>", methods=["GET", "POST"])
@login_required
def catch_pokemon(name):
    print(name)
    pokemon = Post.query.filter_by(name=name).first()
    if len(current_user.team.all()) < 6 and pokemon not in current_user.team:
        current_user.team.append(pokemon)
        db.session.commit()
    return redirect(url_for('post.team'))

@post.route("/remove_pokemon/<name>", methods=["GET", "POST"])
@login_required
def remove_pokemon(name):
    print(name)
    pokemon = Post.query.filter_by(name=name).first()
    current_user.team.remove(pokemon)
    db.session.commit()
    return redirect(url_for('post.team'))

@post.route("/team")
@login_required
def team():
    return render_template('team.html', team=current_user.team.all())



# pokemon_battle_route

# delete_pokemon_route

# edit_pokemon_route

Flask_app/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titile%}{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {%block styles%}{%endblock%}
</head>
<body>
    {%block content%}
    
    {%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>    
</body>
</html>

Flask_app/app/templates/home.html
{%extends 'base.html'%}

{%block title%}
    Home
{%endblock%}

{%block content%}
    {%include './includes/nav.html'%}
    <h1>Pokemon Battle!</h1>

{%endblock%}    

Flask_app/app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Pokemon Battle</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{{url_for('main.pokemon')}}">View Pokemon</a>
            </li>
            {% if current_user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link active" href="{{url_for('auth.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('auth.signup')}}">Sign Up</a>
            </li>
            {%else%}
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('post.pokemon')}}">Select Pokemon</a>
          </li>
          {%endif%}
        </ul>
      </div>
      {% if current_user.is_authenticated %}
      <h4 class="mr-3">{{ current_user.username }}</h4>
      {%endif%}
    </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

Flask_app/app/templates/login.html
{%extends "base.html"%}

{%block title%}
    Login
{%endblock%}

{%block styles%}
<link rel="stylesheet" href="../static/login.css">
{%endblock%}

{%block content%}
    {%include './includes/nav.html'%}
    <div class="flex-container">
    <form method="POST">
      {{ form.hidden_tag()}}
        <div class="mb-3">
          <label for="email" class="form-label">Email address</label>
          {{ form.email(class="form-control", id="email") }}
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          {{ form.password(class="form-control", id="password")}}
        </div>
        {{ form.submit_btn(class='btn my-btn') }}
      </form>
    </div>
{%endblock%}

Flask_app/app/templates/pokemon.html
{%extends 'base.html'%}

{%block title%}
 View Pokemon
{%endblock%}

{%block styles%}
<link rel="stylesheet" href="../static/login.css">
{%endblock%}

{%block content%}
{%include './includes/nav.html'%}
<div class="flex-container">
<form method="POST">
    <div class="mb-3">
      <label for="pokemon" class="form-label"> View Pokemon!</label>
      <input type="text" class="form-control" id="pokemon" name="pokemon">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

  {% if pokemon %}
  <p>{{pokemon}}</p>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Ability</th>
        <th scope="col">Base HP</th>
        <th scope="col">Base Attack</th>
        <th scope="col">Base Defense</th>
        <th scope="col">Experience</th>
        <th scope="col">Photo</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>{{pokemon['name']}}</td>
        <td>{{pokemon['ability']}}</td>
        <td>{{pokemon['base_hp']}}</td>
        <td>{{pokemon['base_attack']}}</td>
        <td>{{pokemon['base_defense']}}</td>
        <td>{{pokemon['base_exp']}}</td>
        <td><img src="{{pokemon['sprite_url']}}"></td>
        <td>
          <a href="{{url_for('post.add_team', user_id=current_user.id, pokemon_id=pokemon['id']) }}" class="btn btn-primary">Add</a>
          <a href="{{url_for('post.remove_team', user_id=current_user.id, pokemon_id=pokemon['id']) }}" class="btn btn-primary">Remove</a>
        </td>
      </tr>
    </tbody>
  </table>
  {%endif%}


{%endblock%}

Flask_app/app/templates/signup.html
{%extends "base.html"%}

{%block title%}
    Sign Up
{%endblock%}

{%block styles%}
<link rel="stylesheet" href="../static/login.css">
{%endblock%}

{%block content%}
    {%include './includes/nav.html'%}
    <div class="flex-container">
    <form method="POST">
      {{ form.hidden_tag()}}
      <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        {{ form.username(class="form-control", id="username")}}
      </div>
        <div class="mb-3">
          <label for="email" class="form-label">Email address</label>
          {{ form.email(class="form-control", id="email")}}
        </div>
        <div class="mb-3">
          <label for="Password" class="form-label">Password</label>
          {{ form.password(class="form-control", id="password")}}
        </div>
        {{ form.submit_btn(class='btn my-btn')}}
      </form>
    </div>
{%endblock%}